visageSDK: VisageSDK::VisageRendering Class Reference
VisageSDK::VisageRendering Class Reference
VisageRendering displays the current frame and the following tracking results using OpenGL.
#include <VisageRendering.h>
Static Public Member Functions
static void DisplayResults (FaceData *trackingData, int trackStat, int width, int height, int drawingOptions=DISPLAY_ALL)
Method calls other methods for drawing the frame and tracking results.
static void DisplayFrame (const IplImage *image, int width, int height)
Method draws the current frame.
static void DisplayFeaturePoints (FaceData *trackingData, int width, int height, bool _3D=false, bool relative=false)
Method draws facial feature points.
static void DisplaySplines (FaceData *trackingData, int width, int height)
Method draws splines.
static void DisplayGaze (FaceData *trackingData, int width, int height)
Method draws the gaze direction.
static void DisplayModelAxes (FaceData *trackingData, int width, int height)
Method draws model axes.
static void DisplayWireFrame (FaceData *trackingData, int width, int height)
Method draws face model.
static void CalcSpline (vector< float > &inputPoints, int ratio, vector< float > &outputPoints)
Method returns vector of calculated spline points.
static void DisplayResults (FaceData *trackingData, int trackStat, int width, int height, int drawingOptions=DISPLAY_ALL)
Method calls other methods for drawing the frame and tracking results.
static void DisplayFrame (const IplImage *image, int width, int height)
Method draws the current frame.
static void DisplayFeaturePoints (FaceData *trackingData, int width, int height, bool _3D=false, bool relative=false)
Method draws facial feature points.
static void DisplaySplines (FaceData *trackingData, int width, int height)
Method draws splines.
static void DisplayGaze (FaceData *trackingData, int width, int height)
Method draws the gaze direction.
static void DisplayModelAxes (FaceData *trackingData, int width, int height)
Method draws model axes.
static void DisplayWireFrame (FaceData *trackingData, int width, int height)
Method draws face model.
static void CalcSpline (vector< float > &inputPoints, int ratio, vector< float > &outputPoints)
Method returns vector of calculated spline points.
Detailed Description
VisageRendering displays the current frame and the following tracking results using OpenGL.
facial feature points
eye closure
gaze direction
model axes Adjacent facial feature points are connected with splines that are calculated using implementation of a Catmull-Rom method
Definition at line 77 of file OpenGL/source/common/VisageRendering.h.
Member Function Documentation
void VisageSDK::VisageRendering::CalcSpline (vector< float > & inputPoints, int ratio, vector< float > & outputPoints) static
Method returns vector of calculated spline points.
Parameters
inputPoints - vector of points which need to be connected with a spline
ratio - number of spline points that need to be calculated between neighbouring input points
outputPoints - vector of calculated spline points
Definition at line 1099 of file VisageRendering.cpp.
static void VisageSDK::VisageRendering::CalcSpline (vector< float > & inputPoints, int ratio, vector< float > & outputPoints) static
Method returns vector of calculated spline points.
Parameters
inputPoints - vector of points which need to be connected with a spline
ratio - number of spline points that need to be calculated between neighbouring input points
outputPoints - vector of calculated spline points
void VisageSDK::VisageRendering::DisplayFeaturePoints (FaceData * trackingData, int width, int height, bool _3D = false, bool relative = false) static
Method draws facial feature points.
Parameters
trackingData - tracking results
width - adjusted width of the OpenGL window
height - adjusted height of the OpenGL window
_3D - use 3D feature points
relative - use relative 3D feature points
Definition at line 563 of file VisageRendering.cpp.
References VisageSDK::FaceData::cameraFocus, VisageSDK::FaceData::eyeClosure, VisageSDK::FaceData::faceRotation, and VisageSDK::FaceData::faceTranslation.
Referenced by DisplayResults().
static void VisageSDK::VisageRendering::DisplayFeaturePoints (FaceData * trackingData, int width, int height, bool _3D = false, bool relative = false) static
Method draws facial feature points.
Parameters
trackingData - tracking results
width - adjusted width of the OpenGL window
height - adjusted height of the OpenGL window
_3D - use 3D feature points
relative - use relative 3D feature points
static void VisageSDK::VisageRendering::DisplayFrame (const IplImage * image, int width, int height) static
Method draws the current frame.
Parameters
image - image for drawing
width - adjusted width of the OpenGL window
height - adjusted height of the OpenGL window
void VisageSDK::VisageRendering::DisplayFrame (const IplImage * image, int width, int height) static
Method draws the current frame.
Parameters
image - image for drawing
width - adjusted width of the OpenGL window
height - adjusted height of the OpenGL window
Definition at line 450 of file VisageRendering.cpp.
Referenced by DisplayResults().
void VisageSDK::VisageRendering::DisplayGaze (FaceData * trackingData, int width, int height) static
Method draws the gaze direction.
Parameters
trackingData - tracking results
width - adjusted width of the OpenGL window
height - adjusted height of the OpenGL window
Definition at line 890 of file VisageRendering.cpp.
References VisageSDK::FaceData::cameraFocus, VisageSDK::FeaturePoint::defined, VisageSDK::FaceData::eyeClosure, VisageSDK::FaceData::featurePoints3D, VisageSDK::FaceData::gazeDirectionGlobal, VisageSDK::FDP::getFP(), and VisageSDK::FeaturePoint::pos.
Referenced by DisplayResults().
static void VisageSDK::VisageRendering::DisplayGaze (FaceData * trackingData, int width, int height) static
Method draws the gaze direction.
Parameters
trackingData - tracking results
width - adjusted width of the OpenGL window
height - adjusted height of the OpenGL window
void VisageSDK::VisageRendering::DisplayModelAxes (FaceData * trackingData, int width, int height) static
Method draws model axes.
Parameters
trackingData - tracking results
width - adjusted width of the OpenGL window
height - adjusted height of the OpenGL window
Definition at line 976 of file VisageRendering.cpp.
References VisageSDK::FaceData::cameraFocus, VisageSDK::FaceData::faceRotation, VisageSDK::FaceData::faceTranslation, VisageSDK::FaceData::featurePoints3D, VisageSDK::FDP::getFP(), and VisageSDK::FeaturePoint::pos.
Referenced by DisplayResults().
static void VisageSDK::VisageRendering::DisplayModelAxes (FaceData * trackingData, int width, int height) static
Method draws model axes.
Parameters
trackingData - tracking results
width - adjusted width of the OpenGL window
height - adjusted height of the OpenGL window
static void VisageSDK::VisageRendering::DisplayResults (FaceData * trackingData, int trackStat, int width, int height, int drawingOptions = DISPLAY_ALL) static
Method calls other methods for drawing the frame and tracking results.
Parameters
trackingData - tracking results
trackStat - tracker status
width - width of the OpenGL window, adjusted so that the aspect of the drawing frame is perserved
height - height of the OpenGL window, adjusted so that the aspect of the drawing frame is perserved
drawingOptions - enables user to choose what tracking results to display; by default all the tracking results are displayed
void VisageSDK::VisageRendering::DisplayResults (FaceData * trackingData, int trackStat, int width, int height, int drawingOptions = DISPLAY_ALL) static
Method calls other methods for drawing the frame and tracking results.
Parameters
trackingData - tracking results
trackStat - tracker status
width - width of the OpenGL window, adjusted so that the aspect of the drawing frame is perserved
height - height of the OpenGL window, adjusted so that the aspect of the drawing frame is perserved
drawingOptions - enables user to choose what tracking results to display; by default all the tracking results are displayed
Definition at line 1145 of file VisageRendering.cpp.
References DisplayFeaturePoints(), DisplayFrame(), DisplayGaze(), DisplayModelAxes(), DisplaySplines(), DisplayWireFrame(), and VisageSDK::FaceData::frame.
Referenced by TrackerWrapper::displayTrackingResults:Status:Info:.
void VisageSDK::VisageRendering::DisplaySplines (FaceData * trackingData, int width, int height) static
Method draws splines.
Parameters
trackingData - tracking results
width - adjusted width of the OpenGL window
height - adjusted height of the OpenGL window
Definition at line 721 of file VisageRendering.cpp.
Referenced by DisplayResults().
static void VisageSDK::VisageRendering::DisplaySplines (FaceData * trackingData, int width, int height) static
Method draws splines.
Parameters
trackingData - tracking results
width - adjusted width of the OpenGL window
height - adjusted height of the OpenGL window
static void VisageSDK::VisageRendering::DisplayWireFrame (FaceData * trackingData, int width, int height) static
Method draws face model.
Parameters
trackingData - tracking results
width - adjusted width of the OpenGL window
height - adjusted height of the OpenGL window
void VisageSDK::VisageRendering::DisplayWireFrame (FaceData * trackingData, int width, int height) static
Method draws face model.
Parameters
trackingData - tracking results
width - adjusted width of the OpenGL window
height - adjusted height of the OpenGL window
Definition at line 1045 of file VisageRendering.cpp.
References VisageSDK::FaceData::cameraFocus, VisageSDK::FaceData::faceModelTriangleCount, VisageSDK::FaceData::faceModelTriangles, VisageSDK::FaceData::faceModelVertices, VisageSDK::FaceData::faceRotation, and VisageSDK::FaceData::faceTranslation.
Referenced by DisplayResults().
The documentation for this class was generated from the following files:
OpenGL/source/common/VisageRendering.h
iOS/VisageTrackerDemo/Classes/VisageRendering.h
VisageRendering.cpp